name: cointwitter
on:
  push:
    branches:
      - release
jobs:
  build:
runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify